pipeline {

    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
    - cat
    tty: true
'''
        }
    }

    environment {
        IMAGE = "gagana1994/devops-microservice-app"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build and Push Image') {
            steps {
                container('kaniko') {
                    sh '''
                    /kaniko/executor \
                      --dockerfile=app/backend/Dockerfile \
                      --context=$(pwd) \
                      --destination=$IMAGE:latest \
                      --insecure \
                      --skip-tls-verify
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                curl -LO https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
                chmod +x kubectl

                ./kubectl rollout restart deployment devops-app
                '''
            }
        }

    }
}
