pipeline {
    agent {
        label 'jenkins-agent'
    }

    stages {
        stage('Test') {
            steps {
                echo "Jenkins Kubernetes agent working"
            }
        }
    }
}
